[KP-680] Generic Trigger
Kaholo/kaholo-trigger-generic pull request #1
Opened 2022-05-16 10:35 UTC by graddaniel

https://kaholo.atlassian.net/browse/KP-680

2022-05-17 10:02 UTC, xkcm submitted a review, later dismissed

2022-05-24 09:35 UTC, kenskyfish requested changes
I was confused while testing, had an active "any" trigger I thought I had deleted. Once actually deleted I see the plugin works flawlessly.

2022-05-24 09:44 UTC, kenskyfish submitted a review, later dismissed
Looks good.

2022-05-25 06:08 UTC, xkcm submitted a review, later dismissed

2022-05-25 09:53 UTC, merged